server:
    port: 8082
    servlet:
        context-path: /
spring:
    thymeleaf:
        encoding: UTF-8
        cache: false
        mode: HTML5
logging:
    level:
        root: INFO
custom:
    serverDomain: http://127.0.0.1:${server.port}

idaas:
    oidc:
#        pkceRequired : true
#        codeChallengeMethod: S256
        client-id:  # IDaaS应用中拿到的 client_id
        client-secret: # IDaaS应用中拿到的 client_secret
        issuer:  # IDaaS应用中拿到的Issuer
#        scopes: openid # IDaaS应用中配置的scopes
        redirect-uri: ${custom.serverDomain}/authentication/login #登录 Redirect URI

